app = "taskbot"
primary_region = "iad"

[env]
  GITHUB_REPO = "pykmintin/Repo"
  PREFIX = "!"
  AUTHORIZED_USER = 367581971053805568

[build]
  dockerfile = "Dockerfile"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
